#!/bin/bash

set -euxo pipefail

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

sudo systemctl stop unattended-upgrades

sudo apt update
sudo apt install -y jq postgresql-client

# install kubectl
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl

# install vault
wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt update
sudo apt install -y vault

# install java
wget https://download.oracle.com/java/23/latest/jdk-23_linux-x64_bin.deb
sudo apt install ./jdk-23_linux-x64_bin.deb

# install maven
wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
tar -xvf apache-maven-3.9.9-bin.tar.gz
sudo mv apache-maven-3.9.9 /opt
export PATH=/opt/apache-maven-3.9.9/bin:$PATH
echo -e "\nPATH=\"/opt/apache-maven-3.9.9/bin:\$PATH\"" >> ~/.profile

mvn -N wrapper:wrapper
rm -f apache-maven-3.9.9-bin.tar.gz jdk-23_linux-x64_bin.deb mvnw mvnw.cmd