#!/bin/bash

set -euxo pipefail

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

sudo systemctl stop unattended-upgrades

sudo apt update
sudo apt install -y jq postgresql-client unzip

# install kubectl
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl

# install vault
curl -LO https://releases.hashicorp.com/vault/1.21.4/vault_1.21.4_linux_amd64.zip
unzip vault_1.21.4_linux_amd64.zip
chmod +x ./vault
sudo mv ./vault /usr/local/bin/vault

# install java
wget -q https://download.oracle.com/java/23/archive/jdk-23.0.2_linux-x64_bin.deb
sudo apt install ./jdk-23.0.2_linux-x64_bin.deb

# install maven
wget -q https://dlcdn.apache.org/maven/maven-3/3.9.15/binaries/apache-maven-3.9.15-bin.tar.gz
tar -xvf apache-maven-3.9.15-bin.tar.gz
sudo mv apache-maven-3.9.15 /opt
export PATH=/opt/apache-maven-3.9.15/bin:$PATH
echo -e "\nPATH=\"/opt/apache-maven-3.9.15/bin:\$PATH\"" >> ~/.profile

mvn -N wrapper:wrapper

rm -f vault_1.21.4_linux_amd64.zip apache-maven-3.9.15-bin.tar.gz jdk-23.0.2_linux-x64_bin.deb mvnw mvnw.cmd