apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
---
apiVersion: v1
data:
  application.properties: |
    spring.application.name=workshop-spring-vault
    
    spring.main.allow-bean-definition-overriding=true
    
    spring.cloud.vault.uri=http://vault.default.svc.cluster.local:8200
    spring.cloud.vault.fail-fast=true
    spring.cloud.vault.authentication: KUBERNETES
    spring.cloud.vault.kubernetes.role: payments
    
    custom.transit.path=transit
    custom.transit.key=payments
    custom.refresh-interval-ms=180000
    
    spring.config.import=vault://
    
    spring.cloud.vault.kv.enabled=true
    spring.cloud.vault.kv.backend=secret
    spring.cloud.vault.kv.application-name=workshop-spring-vault
    
    spring.cloud.vault.database.enabled=true
    spring.cloud.vault.database.role=writer
    spring.cloud.vault.database.backend=database
    
    spring.cloud.vault.config.lifecycle.min-renewal=30s
    spring.cloud.vault.config.lifecycle.expiry-threshold=10s
    
    spring.datasource.url=jdbc:postgresql:///10.5.0.3:5432/payments
kind: ConfigMap
metadata:
  name: payments-config
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      serviceAccountName: payments
      automountServiceAccountToken: true
      containers:
        - image: rosemarywang/spring-vault-example:v0.0.1
          name: payments
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: payments-config