version: "3"
virtualmachines:
- name: sandbox
  image: instruqt/docker-2010
  shell: bash
  environment:
    KUBECONFIG: ~/workshop-spring-vault/tmp/kubeconfig.yaml
    VAULT_ADDR: http://127.0.0.1:8200
    VAULT_TOKEN: root-token
  machine_type: n1-standard-1
