#!/bin/bash
set -euxo pipefail

if [ "$( vault kv get -field=custom.StaticSecret.username secret/workshop-spring-vault )" != "nic" ]; then
  fail-message "Write the correct username configuration property to \`secret/workshop-spring-vault\`"
fi

if [ "$( vault kv get -field=custom.StaticSecret.password secret/workshop-spring-vault )" != "H@rdT0Gu3ss" ]; then
  fail-message "Write the correct password configuration property to \`secret/workshop-spring-vault\`"
fi