#!/bin/bash
set -euxo pipefail

set-workdir /root/workshop-spring-vault

if ! grep "@EnableScheduling" src/main/java/com/example/workshop_spring_vault/WorkshopSpringVaultApplication.java; then
    fail-message "Add \`@EnableScheduling\` to main file to support scheduled task to refresh secret"
fi

if ! grep "@RefreshScope\s*ExampleClient" src/main/java/com/example/workshop_spring_vault/WorkshopSpringVaultApplication.java; then
    fail-message "Add \`@RefreshScope\` to main file to refresh ExampleClient with new secrets"
fi